repos:
  # pre-commit inbuilt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: name-tests-test
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer
      - id: detect-aws-credentials
      - id: detect-private-key


  # auto code formating
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black

  # applies the black formatting to documentation file
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==21.6b0]

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
    -   id: autopep8


  # A tool (and pre-commit hook) to automatically upgrade syntax for newer versions of the language.
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.19.4
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  # sorting the import libraries
  - repo: https://github.com/pycqa/isort
    rev: 5.9.1
    hooks:
      - id: isort


  # static code analysis
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports, --python-version=3.8]

  # security check

  # - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
  #   rev: v1.0.4
  #   hooks:
  #   -   id: python-bandit-vulnerability-check
